name: ci
on:
  push:
    paths:
      ["**.go", "go.*", "**/testdata/**", ".git*", ".github/workflows/ci.yml"]
  pull_request:
    paths:
      ["**.go", "go.*", "**/testdata/**", ".git*", ".github/workflows/ci.yml"]
env:
  GOFLAGS: "-mod=vendor"

jobs:
  unit-test:
    strategy:
      matrix:
        go: [1.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Read environment
        run: |
          echo "::set-output name=gocache::$(go env GOCACHE)"
          echo "::set-output name=ver::$ImageVersion $(go version)"
        shell: bash
        id: env
      - uses: actions/cache@v1
        with:
          path: ${{ steps.env.outputs.gocache }}
          key: ${{ matrix.os }} ${{ steps.env.outputs.ver }} ${{ hashFiles('go.sum') }}

      - run: go test ./...
        shell: bash

  build-minisign:
    runs-on: ubuntu-latest

    steps:
      - name: Install libsodium headers
        run: sudo apt install libsodium-dev
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
          repository: jedisct1/minisign
          ref: master

      - name: Compile
        run: |
          gcc -O2 -s -w -o minisign "$RUNNER_WORKSPACE"/minisign/src/*.c -lsodium
          file minisign
          ./minisign -v
      - name: Sign
        run: echo | ./minisign -Ss <(echo "$MINISIGN_SK") -t "timestamp:$(date +%s) trigger:$GITHUB_EVENT_NAME actor:$GITHUB_ACTOR url:https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA" -m minisign
        env:
          MINISIGN_SK: ${{ secrets.MINISIGN_SK }}
      - uses: actions/upload-artifact@v1
        with:
          name: minisign
          path: .
